# Generated by Django 3.2.18 on 2023-04-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
