# Generated by Django 3.2.18 on 2023-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='Your email here.', max_length=254),
        ),
    ]
