# Generated by Django 3.2.18 on 2023-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='persons',
            field=models.BigIntegerField(blank=True, default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(blank=True, default='0', max_length=12),
        ),
    ]
