# Generated by Django 3.2.18 on 2023-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20230530_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.BigIntegerField(blank=True, default='0', max_length=12),
        ),
    ]
