# Generated by Django 3.2.18 on 2023-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20230612_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
